// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWxtnBHNaXKZ35Th9nv372CTrD0XFCxNo',
    appId: '1:960729316618:web:dd4867b670d8288fe68ef3',
    messagingSenderId: '960729316618',
    projectId: 'projeto3-6cda9',
    authDomain: 'projeto3-6cda9.firebaseapp.com',
    databaseURL: 'https://projeto3-6cda9-default-rtdb.firebaseio.com',
    storageBucket: 'projeto3-6cda9.appspot.com',
    measurementId: 'G-QZLWSBS7DY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmKyrNNm4RVVDZ-xEQoWQ_jE9zjDkP6lE',
    appId: '1:960729316618:android:1c43bbec8cb97644e68ef3',
    messagingSenderId: '960729316618',
    projectId: 'projeto3-6cda9',
    databaseURL: 'https://projeto3-6cda9-default-rtdb.firebaseio.com',
    storageBucket: 'projeto3-6cda9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH1zNL9Ab3bOw6JEpD4gedHML-_kveat4',
    appId: '1:960729316618:ios:25df8f2246cfb529e68ef3',
    messagingSenderId: '960729316618',
    projectId: 'projeto3-6cda9',
    databaseURL: 'https://projeto3-6cda9-default-rtdb.firebaseio.com',
    storageBucket: 'projeto3-6cda9.appspot.com',
    iosBundleId: 'com.example.projeto2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCH1zNL9Ab3bOw6JEpD4gedHML-_kveat4',
    appId: '1:960729316618:ios:68b224406f8ffb43e68ef3',
    messagingSenderId: '960729316618',
    projectId: 'projeto3-6cda9',
    databaseURL: 'https://projeto3-6cda9-default-rtdb.firebaseio.com',
    storageBucket: 'projeto3-6cda9.appspot.com',
    iosBundleId: 'com.example.projeto2.RunnerTests',
  );
}
